services:
  - type: web
    name: diabete-alerte
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 127.0.0.1:5000 app:diabete-alerte"
    envVars:
      - key: MONGO_URI
        value: mongodb://localhost:27017/diabeteAlertDB
      - key: SECRET_KEY
        value: diabeteAlert