services:
  - type: web
    name: diabete-alerte
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 app:app"
    envVars:
      - key: MONGO_URI
        value: "mongodb://jokaneadx:Dfaienebd1324nxq348Js1%23s@157.173.106.139:2190/diabeteAlertDB"
      - key: SECRET_KEY
        value: diabeteAlert